#include "fpp.h"
void process_batch(int *key_lo)
{
	int success[BATCH_SIZE];
	int bkt_2[BATCH_SIZE];
	int bkt_1[BATCH_SIZE];
	int i[BATCH_SIZE];
	int key[BATCH_SIZE];

	int I = 0;			// batch index
	void *batch_rips[BATCH_SIZE];		// goto targets
	int iMask = 0;		// No packet is done yet

	int temp_index;
	for(temp_index = 0; temp_index < BATCH_SIZE; temp_index ++) {
		batch_rips[temp_index] = &&fpp_start;
	}

fpp_start:

        success[I] = 0;
        key[I] = key_lo[I];
        
        /** < Try the first bucket */
        bkt_1[I] = hash(key[I]) & NUM_BKT_;
        FPP_PSS(&ht_index[bkt_1[I]], fpp_label_1);
fpp_label_1:

        for(i[I] = 0; i[I] < 8; i[I] ++) {
            if(ht_index[bkt_1[I]].slot[i[I]].key == key[I]) {
                sum += ht_index[bkt_1[I]].slot[i[I]].value;
                succ_1 ++;
                success[I] = 1;
                break;
            }
        }
        
        if(success[I] == 0) {
            bkt_2[I] = hash(bkt_1[I]) & NUM_BKT_;
            FPP_PSS(&ht_index[bkt_2[I]], fpp_label_2);
fpp_label_2:

            for(i[I] = 0; i[I] < 8; i[I] ++) {
                if(ht_index[bkt_2[I]].slot[i[I]].key == key[I]) {
                    sum += ht_index[bkt_2[I]].slot[i[I]].value;
                    succ_2 ++;
                    success[I] = 1;
                    break;
                }
            }
        }
        
        if(success[I] == 0) {
            fail ++;
        }
    
fpp_end:
    batch_rips[I] = &&fpp_end;
    iMask = FPP_SET(iMask, I); 
    if(iMask == (1 << BATCH_SIZE) - 1) {
        return;
    }
    I = (I + 1) & BATCH_SIZE_;
    goto *batch_rips[I];

}

