#include "fpp.h"
void process_batch(struct node *nodes)
{
	int next_nbh[BATCH_SIZE];
	int i[BATCH_SIZE];
	struct node *cur_node[BATCH_SIZE];

	int I = 0;			// batch index
	void *batch_rips[BATCH_SIZE];		// goto targets
	int iMask = 0;		// No packet is done yet

	int temp_index;
	for(temp_index = 0; temp_index < BATCH_SIZE; temp_index ++) {
		batch_rips[temp_index] = &&fpp_start;
	}

fpp_start:

        cur_node[I] = &nodes[I];
        
        for(i[I] = 0; i[I] < STEPS; i[I] ++) {
            FPP_PSS(cur_node[I], fpp_label_1);
fpp_label_1:

            sum += cur_node[I]->id;
            
            /** < Compute the next neighbor */
            next_nbh[I] = -1;
            while(next_nbh[I] < 0) {
                next_nbh[I] = rand() % 7;
            }
            
            cur_node[I] = (struct node *) nodes[I].neighbors[next_nbh[I]];
        }
        
fpp_end:
    batch_rips[I] = &&fpp_end;
    iMask = FPP_SET(iMask, I); 
    if(iMask == (1 << BATCH_SIZE) - 1) {
        return;
    }
    I = (I + 1) & BATCH_SIZE_;
    goto *batch_rips[I];

}

