//
// ipv4_rtable_vec.h
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#ifndef ISPC_IPV4_RTABLE_VEC_H
#define ISPC_IPV4_RTABLE_VEC_H

#include <stdint.h>



#ifdef __cplusplus
namespace ispc { /* namespace */
#endif // __cplusplus
#ifndef __ISPC_STRUCT_ipv4_rtable__
#define __ISPC_STRUCT_ipv4_rtable__
struct ipv4_rtable {
    uint32_t n;
    uint8_t fallback_port_id;
    struct ipv4_rtable_entry * entries;
};
#endif

#ifndef __ISPC_STRUCT_ipv4_rtable_entry__
#define __ISPC_STRUCT_ipv4_rtable_entry__
struct ipv4_rtable_entry {
    uint8_t port_id;
    uint32_t children[16];
};
#endif


///////////////////////////////////////////////////////////////////////////
// Functions exported from ispc code
///////////////////////////////////////////////////////////////////////////
#if defined(__cplusplus) && !defined(__ISPC_NO_EXTERN_C)
extern "C" {
#endif // __cplusplus
    extern void ipv4_rtable_lookup_vec(struct ipv4_rtable * rtable, uint32_t n, uint32_t * addr_array, uint8_t * port_id_array);
#if defined(__cplusplus) && !defined(__ISPC_NO_EXTERN_C)
} /* end extern C */
#endif // __cplusplus


#ifdef __cplusplus
} /* namespace */
#endif // __cplusplus

#endif // ISPC_IPV4_RTABLE_VEC_H
